#!/usr/bin/env bash
#
# First boot: fetch Moodle core, write config.php, install the site, enable the
# plugin. Every boot after that: run any pending upgrade and get out of the way.
#
# Every step is idempotent, so `docker compose up` on an existing stack is fast
# and non-destructive.

set -euo pipefail

MOODLE_DIR=/var/www/html
MOODLE_BRANCH="${MOODLE_BRANCH:-MOODLE_401_STABLE}"
MOODLE_WWWROOT="${MOODLE_WWWROOT:-http://localhost:8080}"
DATAROOT=/var/www/moodledata

log() { printf '\033[36m[simplemcp]\033[0m %s\n' "$*"; }
die() { printf '\033[31m[simplemcp] %s\033[0m\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# 1. Wait for PostgreSQL.
# ---------------------------------------------------------------------------
log "Waiting for database ${DB_HOST}..."
for _ in $(seq 1 60); do
    if pg_isready -h "${DB_HOST}" -U "${DB_USER}" -d "${DB_NAME}" -q; then
        break
    fi
    sleep 2
done
pg_isready -h "${DB_HOST}" -U "${DB_USER}" -d "${DB_NAME}" -q || die "database never became ready"

# ---------------------------------------------------------------------------
# 2. Fetch Moodle core into the (empty on first boot) source volume.
#
# local/simplemcp is a live bind mount from the host, so core cannot simply be
# cloned on top: rsync merges core in and leaves the mounted plugin untouched.
# ---------------------------------------------------------------------------
if [ ! -f "${MOODLE_DIR}/version.php" ]; then
    log "Fetching Moodle core (${MOODLE_BRANCH}) — first boot only, this takes a few minutes..."
    rm -rf /tmp/moodle-src
    git clone --depth 1 --branch "${MOODLE_BRANCH}" \
        https://github.com/moodle/moodle.git /tmp/moodle-src \
        || die "could not clone Moodle branch ${MOODLE_BRANCH}"

    rsync -a --exclude 'local/simplemcp' /tmp/moodle-src/ "${MOODLE_DIR}/"
    rm -rf /tmp/moodle-src

    CORE_RELEASE="$(grep -oP "^\\\$release\s*=\s*'\K[^']+" "${MOODLE_DIR}/version.php" || echo unknown)"
    log "Moodle core installed: ${CORE_RELEASE}"
fi

if [ ! -e "${MOODLE_DIR}/local/simplemcp/version.php" ]; then
    die "local/simplemcp is not mounted — check the bind mount in docker-compose.yml"
fi

mkdir -p "${DATAROOT}" /var/www/phpu_moodledata /var/www/behat_moodledata /var/www/behat_faildumps
chown -R www-data:www-data "${DATAROOT}" /var/www/phpu_moodledata /var/www/behat_moodledata /var/www/behat_faildumps

# ---------------------------------------------------------------------------
# 3. config.php — regenerated every boot so changing a compose env var
#    (a different port, say) actually takes effect.
# ---------------------------------------------------------------------------
log "Writing config.php"
cat > "${MOODLE_DIR}/config.php" <<PHP
<?php
// Generated by dev/docker/entrypoint.sh. Do not edit; edit docker-compose.yml.
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();

\$CFG->dbtype    = 'pgsql';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = '${DB_HOST}';
\$CFG->dbname    = '${DB_NAME}';
\$CFG->dbuser    = '${DB_USER}';
\$CFG->dbpass    = '${DB_PASS}';
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = ['dbpersist' => 0, 'dbport' => 5432, 'dbsocket' => ''];

\$CFG->wwwroot   = '${MOODLE_WWWROOT}';
\$CFG->dataroot  = '${DATAROOT}';
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02777;

// Developer debugging: the MCP endpoint deliberately allows plain HTTP only
// when DEBUG_DEVELOPER is on, which is what makes http://localhost usable.
\$CFG->debug = (E_ALL | E_STRICT);
\$CFG->debugdisplay = 1;
\$CFG->cachejs = false;
\$CFG->themedesignermode = false;
\$CFG->passwordpolicy = false;

// PHPUnit.
\$CFG->phpunit_prefix = 'phpu_';
\$CFG->phpunit_dataroot = '/var/www/phpu_moodledata';

// Behat.
\$CFG->behat_prefix = 'bht_';
\$CFG->behat_dataroot = '/var/www/behat_moodledata';
\$CFG->behat_wwwroot = '${BEHAT_WWWROOT:-http://moodle/behat}';
\$CFG->behat_faildump_path = '/var/www/behat_faildumps';
\$CFG->behat_profiles = [
    'chrome' => [
        'browser' => 'chrome',
        'wd_host' => '${SELENIUM_URL:-http://selenium:4444/wd/hub}',
        'capabilities' => [
            'extra_capabilities' => [
                'chromeOptions' => [
                    'args' => ['--no-sandbox', '--disable-dev-shm-usage', '--window-size=1920,1080'],
                ],
            ],
        ],
    ],
];

require_once(__DIR__ . '/lib/setup.php');
PHP
chown www-data:www-data "${MOODLE_DIR}/config.php"

# ---------------------------------------------------------------------------
# 4. Install the site, or upgrade it if core/plugin versions moved.
# ---------------------------------------------------------------------------
run_as_web() { su -s /bin/bash www-data -c "$*"; }

# Moodle has no CLI script that answers "is this site installed?", and booting
# it to ask fails when it is not. Asking the database directly is the only
# check that works in both states.
site_installed() {
    PGPASSWORD="${DB_PASS}" psql -h "${DB_HOST}" -U "${DB_USER}" -d "${DB_NAME}" \
        -tAc "SELECT 1 FROM mdl_config LIMIT 1" >/dev/null 2>&1
}

if ! site_installed; then
    log "Installing Moodle site (first boot only)..."
    run_as_web "php ${MOODLE_DIR}/admin/cli/install_database.php \
        --agree-license \
        --adminuser='${MOODLE_ADMIN_USER}' \
        --adminpass='${MOODLE_ADMIN_PASSWORD}' \
        --adminemail='${MOODLE_ADMIN_EMAIL}' \
        --fullname='Simple MCP Dev' \
        --shortname='simplemcp-dev' \
        --summary='Local development site for local_simplemcp.'"
    log "Site installed. Admin login: ${MOODLE_ADMIN_USER} / ${MOODLE_ADMIN_PASSWORD}"
else
    log "Running any pending upgrades..."
    run_as_web "php ${MOODLE_DIR}/admin/cli/upgrade.php --non-interactive --allow-unstable" || true
fi

# ---------------------------------------------------------------------------
# 5. Turn the plugin on. A dev site with the endpoint disabled is useless, and
#    these are exactly the settings the README tells an admin to tick.
# ---------------------------------------------------------------------------
log "Enabling local_simplemcp"
set_cfg() { run_as_web "php ${MOODLE_DIR}/admin/cli/cfg.php --component=local_simplemcp --name=$1 --set=$2" >/dev/null; }
set_cfg enabled 1
set_cfg enabletesttokens 1
set_cfg enableoauth 1
set_cfg enabledynamicregistration 1
set_cfg enabledcontenttypes lesson,page,book
set_cfg servername simplemcp-dev

run_as_web "php ${MOODLE_DIR}/admin/cli/purge_caches.php" >/dev/null

log "Ready → ${MOODLE_WWWROOT}"
log "MCP endpoint → ${MOODLE_WWWROOT}/local/simplemcp/endpoint.php"

exec "$@"
